name: 🏷️ Auto-label by Component
on:
  issues:
    types: [opened, edited]

jobs:
  label-by-component:
    runs-on: ubuntu-latest
    steps:
      - name: Extract component and apply label
        uses: actions/github-script@v7
        with:
          script: |
            const componentField = context.payload.issue.body.match(/### Which component is this issue related to\?\n\n(.+)/);
            if (!componentField) return;

            const componentMap = {
              "Umbraco.Cms.Integrations": "component/cms",
              "Umbraco.Forms.Integrations": "component/forms",
              "Umbraco.AuthorizedServices": "component/auth"
            };

            const selected = componentField[1].trim();
            const label = componentMap[selected];
            if (label) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [label]
              });
            }